// Auto-generated by: bun run db:types   (requires local stack running via docker compose)
// Manually updated after 20260602175001_inventory migration — regenerate when local stack is available.
export type Database = {
    public: {
        Tables: {
            player_inventory: {
                Row: {
                    user_id: string;
                    item_type: "deck_style" | "board_style";
                    item_id: string;
                    acquired_at: string;
                };
                Insert: {
                    user_id: string;
                    item_type: "deck_style" | "board_style";
                    item_id: string;
                    acquired_at?: string;
                };
                Update: {
                    user_id?: string;
                    item_type?: "deck_style" | "board_style";
                    item_id?: string;
                    acquired_at?: string;
                };
                Relationships: [
                    {
                        foreignKeyName: "player_inventory_user_id_fkey";
                        columns: ["user_id"];
                        referencedRelation: "profiles";
                        referencedColumns: ["id"];
                    },
                ];
            };
            deck_styles: {
                Row: {
                    id: string;
                    name: string;
                    tier:
                        | "common"
                        | "uncommon"
                        | "rare"
                        | "epic"
                        | "legendary"
                        | "mystical"
                        | "ethereal";
                    preview_css: Record<string, string> | null;
                    created_at: string;
                };
                Insert: {
                    id: string;
                    name: string;
                    tier?:
                        | "common"
                        | "uncommon"
                        | "rare"
                        | "epic"
                        | "legendary"
                        | "mystical"
                        | "ethereal";
                    preview_css?: Record<string, string> | null;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    name?: string;
                    tier?:
                        | "common"
                        | "uncommon"
                        | "rare"
                        | "epic"
                        | "legendary"
                        | "mystical"
                        | "ethereal";
                    preview_css?: Record<string, string> | null;
                    created_at?: string;
                };
                Relationships: [];
            };
            board_styles: {
                Row: {
                    id: string;
                    name: string;
                    tier:
                        | "common"
                        | "uncommon"
                        | "rare"
                        | "epic"
                        | "legendary"
                        | "mystical"
                        | "ethereal";
                    background_css: string;
                    created_at: string;
                };
                Insert: {
                    id: string;
                    name: string;
                    tier?:
                        | "common"
                        | "uncommon"
                        | "rare"
                        | "epic"
                        | "legendary"
                        | "mystical"
                        | "ethereal";
                    background_css: string;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    name?: string;
                    tier?:
                        | "common"
                        | "uncommon"
                        | "rare"
                        | "epic"
                        | "legendary"
                        | "mystical"
                        | "ethereal";
                    background_css?: string;
                    created_at?: string;
                };
                Relationships: [];
            };
            player_customizations: {
                Row: {
                    user_id: string;
                    deck_style_id: string;
                    board_style_id: string;
                    updated_at: string;
                };
                Insert: {
                    user_id: string;
                    deck_style_id?: string;
                    board_style_id?: string;
                    updated_at?: string;
                };
                Update: {
                    user_id?: string;
                    deck_style_id?: string;
                    board_style_id?: string;
                    updated_at?: string;
                };
                Relationships: [
                    {
                        foreignKeyName: "player_customizations_user_id_fkey";
                        columns: ["user_id"];
                        referencedRelation: "profiles";
                        referencedColumns: ["id"];
                    },
                    {
                        foreignKeyName: "player_customizations_deck_style_id_fkey";
                        columns: ["deck_style_id"];
                        referencedRelation: "deck_styles";
                        referencedColumns: ["id"];
                    },
                    {
                        foreignKeyName: "player_customizations_board_style_id_fkey";
                        columns: ["board_style_id"];
                        referencedRelation: "board_styles";
                        referencedColumns: ["id"];
                    },
                ];
            };
            player_xp: {
                Row: {
                    user_id: string;
                    xp: number;
                    updated_at: string;
                };
                Insert: {
                    user_id: string;
                    xp?: number;
                    updated_at?: string;
                };
                Update: {
                    user_id?: string;
                    xp?: number;
                    updated_at?: string;
                };
                Relationships: [
                    {
                        foreignKeyName: "player_xp_user_id_fkey";
                        columns: ["user_id"];
                        referencedRelation: "profiles";
                        referencedColumns: ["id"];
                    },
                ];
            };
            profiles: {
                Row: {
                    id: string;
                    username: string;
                    avatar_url: string | null;
                    created_at: string;
                };
                Insert: {
                    id: string;
                    username: string;
                    avatar_url?: string | null;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    username?: string;
                    avatar_url?: string | null;
                    created_at?: string;
                };
                Relationships: [];
            };
        };
        Views: Record<string, never>;
        Functions: Record<string, never>;
        Enums: Record<string, never>;
    };
};
