// Auto-generated by: bun run db:types   (requires local stack running via docker compose)
// Manually updated after 20260602174540_player_xp migration — regenerate when local stack is available.
export type Database = {
  public: {
    Tables: {
      player_xp: {
        Row: {
          user_id: string;
          xp: number;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          xp?: number;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          xp?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "player_xp_user_id_fkey";
            columns: ["user_id"];
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          username: string;
          avatar_url: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          username: string;
          avatar_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          avatar_url?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
