import type { CardDescriptor } from "@/lib/card/types";
import type { GameState } from "@/lib/engine/types";

/**
 * ECA (Événement / Condition / Action) — the Game Studio's rule language.
 *
 * An {@link EcaDefinition} is a plain JSON document: it is what the Studio
 * editor produces, what gets stored in the `eca_games` table, and what
 * `createEcaModule` interprets into a regular {@link GameModule}. No code is
 * ever generated — the definition is DATA, validated server-side before any
 * write and re-validated before play.
 *
 * The mental model shown to creators:
 *
 *     QUAND  un joueur joue une carte          ← Événement (event)
 *     SI     sa valeur > dernière carte jouée  ← Condition(s), AND-combined
 *     ALORS  la carte est acceptée             ← Action(s)  (effects)
 */

export const ECA_DEFINITION_VERSION = 1;

/**
 * Decks allowed in v1 — suited-only (no trumps / fool / jokers), so every
 * card has a rank and a suit and conditions stay simple.
 */
export type EcaDeckId = "french52" | "french32";

export type EcaEventType = "cardPlayed" | "turnStarted";

/**
 * A property of a card usable in conditions. `value` is the index of the
 * card's rank in the deck's rank list (ordered low → high) — the numeric
 * strength, comparable with `gt`/`lt`; `rank` and `suit` compare as strings.
 */
export type EcaCardProp = "rank" | "suit" | "value";

export type EcaOperand =
    | {
          readonly kind: "card";
          readonly source: "playedCard" | "topDiscard";
          readonly prop: EcaCardProp;
      }
    | {
          readonly kind: "stat";
          readonly source:
              | "actorHandCount"
              | "drawPileCount"
              | "discardPileCount";
      }
    | { readonly kind: "literal"; readonly value: string | number };

export type EcaComparator = "eq" | "neq" | "gt" | "gte" | "lt" | "lte";

export interface EcaCondition {
    readonly lhs: EcaOperand;
    readonly op: EcaComparator;
    readonly rhs: EcaOperand;
}

export type EcaEffect =
    /** The played card moves to the discard pile (cardPlayed rules only). */
    | { readonly type: "acceptCard" }
    /** Explicit refusal — the play is illegal (cardPlayed rules only). */
    | { readonly type: "rejectCard" }
    /** Immediately draw `count` cards (1..8) into a player's hand. */
    | {
          readonly type: "drawCards";
          readonly target: "actor" | "nextPlayer";
          readonly count: number;
      }
    | { readonly type: "skipNextPlayer" }
    | { readonly type: "reverseDirection" }
    /** The actor keeps the turn (cardPlayed rules only). */
    | { readonly type: "playAgain" }
    | { readonly type: "endGame"; readonly winner: "actor" };

export interface EcaRule {
    /** Stable uuid, generated by the editor — React key + event log identity. */
    readonly id: string;
    /** Creator label, shown in the editor and the in-game log. */
    readonly name: string;
    readonly event: EcaEventType;
    /** AND-combined; an empty list always matches. */
    readonly conditions: readonly EcaCondition[];
    /** Applied in order when the rule fires (1..8). */
    readonly effects: readonly EcaEffect[];
}

export interface EcaDefinition {
    readonly version: 1;
    readonly meta: {
        /** 1..60 chars. */
        readonly name: string;
        /** ≤ 300 chars. */
        readonly description?: string;
        /** 2..8, and min ≤ max. */
        readonly minPlayers: number;
        readonly maxPlayers: number;
    };
    readonly setup: {
        readonly deckId: EcaDeckId;
        /** 1..26; handSize·maxPlayers (+1 if startDiscard) must fit the deck. */
        readonly handSize: number;
        /** Flip the first card of the stock onto the discard at deal time. */
        readonly startDiscard: boolean;
    };
    readonly turn: {
        /** The player may draw one card on their turn (once). */
        readonly allowDraw: boolean;
        /** The player may pass… */
        readonly allowPass: boolean;
        /** …only after drawing this turn (ignored if draw or pass is off). */
        readonly passRequiresDraw: boolean;
        /** Draw pile empty ⇒ reshuffle the discard (minus its top) via rng. */
        readonly reshuffleDiscard: boolean;
    };
    /** 1..32. Order matters: the FIRST matching rule wins. */
    readonly rules: readonly EcaRule[];
    /** v1: first empty hand wins; a blocked game ranks by fewest cards. */
    readonly win: { readonly condition: "emptyHand" };
}

// ── Runtime state / actions / view ───────────────────────────────────────────

export interface EcaState extends GameState {
    /**
     * The interpreted definition, stamped in at setup (président's `rules`
     * pattern): any module instance can resume or replay a saved game from
     * `(definition, seed, action log)` alone.
     */
    readonly definition: EcaDefinition;
    readonly hands: Readonly<Record<string, readonly CardDescriptor[]>>;
    readonly drawPile: readonly CardDescriptor[];
    /** Top of the pile = last element. */
    readonly discardPile: readonly CardDescriptor[];
    /** Turn rotation over seat order: 1 = ascending seats, -1 = descending. */
    readonly direction: 1 | -1;
    /** Skips owed to future turn advancements (skipNextPlayer effects). */
    readonly pendingSkips: number;
    readonly hasDrawnThisTurn: boolean;
    /** Consecutive `pass` actions — a full silent cycle ends a blocked game. */
    readonly consecutivePasses: number;
    /** Filled when the game ends; players sharing rank 1. */
    readonly winnerIds: readonly string[];
}

export type EcaAction =
    | {
          readonly type: "playCard";
          readonly playerId: string;
          readonly card: CardDescriptor;
      }
    | { readonly type: "drawCard"; readonly playerId: string }
    | { readonly type: "pass"; readonly playerId: string };

export interface EcaPlayerView {
    readonly id: string;
    readonly name: string;
    readonly seat: number;
    readonly handCount: number;
    /** Own cards — present only in the viewer's own slot (RLS in code). */
    readonly hand?: readonly CardDescriptor[];
}

/**
 * Public projection of an {@link EcaState}: opponents' hands become counters,
 * the draw pile becomes a count — its order is never leaked. The rules
 * themselves are not secret (they describe the game, not hidden information).
 */
export interface EcaView {
    readonly gameId: string;
    readonly phase: string;
    readonly turn: number;
    readonly currentPlayerId: string | null;
    readonly direction: 1 | -1;
    readonly topDiscard: CardDescriptor | null;
    readonly discardCount: number;
    readonly drawPileCount: number;
    readonly hasDrawnThisTurn: boolean;
    readonly winnerIds: readonly string[];
    readonly definition: {
        readonly name: string;
        readonly rules: ReadonlyArray<{
            readonly id: string;
            readonly name: string;
            readonly event: EcaEventType;
        }>;
    };
    readonly players: readonly EcaPlayerView[];
    /** The viewer this projection was built for (`null` = spectator). */
    readonly self: string | null;
}
